AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla para crear una instancia EC2 en Amazon Web Services

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.medium'
      ImageId: 'ami-0e2c8caa4b6378d8c'
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Grupo de seguridad para la instancia EC2'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: '20'
          ToPort: '20'
          CidrIp: '0.0.0.0/0'
