AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla para crear una instancia EC2 en Amazon Web Services

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.medium'
      ImageId: 'ami-0c02fb55956c7d316' # Reemplaza con la ID de la AMI de tu preferencia
